<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="18" ignored="4" total="28" passed="0" failed="6" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[changepasswordmanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[changepasswordmanufacturer----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[changepasswordmanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[changepasswordmanufacturer----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[changepasswordmanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[changepasswordmanufacturer----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[changepasswordmanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[changepasswordmanufacturer23/11/2023 16-11-46----TestScript execution failed-----]]>
    </line>
    <line>
      <![CDATA[addretailerwithmandatorytextfield----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addretailerwithmandatorytextfield----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[addproductbymanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addretailerwithmandatorytextfield----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addproductbymanufacturer----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[addproductbymanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addretailerwithmandatorytextfield----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[addproductbymanufacturer----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[addproductbymanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addproductbymanufacturer----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[addproductbymanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addproductbymanufacturer23/11/2023 16-11-57----TestScript execution failed-----]]>
    </line>
    <line>
      <![CDATA[addretailerwithmandatorytextfield----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addretailerwithmandatorytextfield----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[addretailerandsearchorder----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addretailerandsearchorder----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[addretailerandsearchorder----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addretailerandsearchorder----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[addretailerandsearchorder----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addretailerandsearchorder----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[addretailerandsearchorder----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addretailerandsearchorder23/11/2023 16-12-05----TestScript execution failed-----]]>
    </line>
    <line>
      <![CDATA[addretailerwithmandatorytextfield----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[addretailerwithmandatorytextfield23/11/2023 16-12-08----TestScript execution failed-----]]>
    </line>
    <line>
      <![CDATA[updatemanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[updatemanufacturer----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[updatemanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[updatemanufacturer----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[updatemanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[updatemanufacturer----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[updatemanufacturer----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[updatemanufacturer23/11/2023 16-12-37----TestScript execution failed-----]]>
    </line>
    <line>
      <![CDATA[checkinvoicebyid----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[checkinvoicebyid----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[checkinvoicebyid----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[checkinvoicebyid----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[checkinvoicebyid----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[checkinvoicebyid----TestScript execution Skipped-----]]>
    </line>
    <line>
      <![CDATA[checkinvoicebyid----TestScript execution strts from here-----]]>
    </line>
    <line>
      <![CDATA[checkinvoicebyid23/11/2023 16-13-08----TestScript execution failed-----]]>
    </line>
  </reporter-output>
  <suite started-at="2023-11-23T16:11:35 IST" name="Suite" finished-at="2023-11-23T16:13:14 IST" duration-ms="99205">
    <groups>
      <group name="regression">
        <method signature="checkinvoicebyidTest.checkinvoicebyid()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" name="checkinvoicebyid" class="com.Procure.Admin.checkinvoicebyidTest"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="addretailerwithmandatorytextfieldTest.addretailerwithmandatorytextfield()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" name="addretailerwithmandatorytextfield" class="com.Procure.Admin.addretailerwithmandatorytextfieldTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-11-23T16:11:35 IST" name="Test" finished-at="2023-11-23T16:12:06 IST" duration-ms="30796">
      <class name="com.Procure.AddProductModule.addproductbymanufacturerTest">
        <test-method is-config="true" signature="bC()[pri:0, instance:com.Procure.AddProductModule.addproductbymanufacturerTest@6e9175d8]" started-at="2023-11-23T16:11:48 IST" name="bC" finished-at="2023-11-23T16:11:54 IST" duration-ms="6056" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bC -->
        <test-method retried="true" signature="addproductbymanufacturer()[pri:0, instance:com.Procure.AddProductModule.addproductbymanufacturerTest@6e9175d8]" started-at="2023-11-23T16:11:54 IST" name="addproductbymanufacturer" finished-at="2023-11-23T16:11:55 IST" duration-ms="1672" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.AddProductModule.addproductbymanufacturerTest.addproductbymanufacturer(addproductbymanufacturerTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addproductbymanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addproductbymanufacturer----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addproductbymanufacturer -->
        <test-method retried="true" signature="addproductbymanufacturer()[pri:0, instance:com.Procure.AddProductModule.addproductbymanufacturerTest@6e9175d8]" started-at="2023-11-23T16:11:55 IST" name="addproductbymanufacturer" finished-at="2023-11-23T16:11:56 IST" duration-ms="533" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.AddProductModule.addproductbymanufacturerTest.addproductbymanufacturer(addproductbymanufacturerTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addproductbymanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addproductbymanufacturer----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addproductbymanufacturer -->
        <test-method retried="true" signature="addproductbymanufacturer()[pri:0, instance:com.Procure.AddProductModule.addproductbymanufacturerTest@6e9175d8]" started-at="2023-11-23T16:11:56 IST" name="addproductbymanufacturer" finished-at="2023-11-23T16:11:56 IST" duration-ms="420" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.AddProductModule.addproductbymanufacturerTest.addproductbymanufacturer(addproductbymanufacturerTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addproductbymanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addproductbymanufacturer----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addproductbymanufacturer -->
        <test-method signature="addproductbymanufacturer()[pri:0, instance:com.Procure.AddProductModule.addproductbymanufacturerTest@6e9175d8]" started-at="2023-11-23T16:11:56 IST" name="addproductbymanufacturer" finished-at="2023-11-23T16:11:57 IST" duration-ms="372" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.AddProductModule.addproductbymanufacturerTest.addproductbymanufacturer(addproductbymanufacturerTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addproductbymanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addproductbymanufacturer23/11/2023 16-11-57----TestScript execution failed-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addproductbymanufacturer -->
      </class> <!-- com.Procure.AddProductModule.addproductbymanufacturerTest -->
      <class name="com.Procure.EditProfileModule.changepasswordmanufacturerTest">
        <test-method is-config="true" signature="bC()[pri:0, instance:com.Procure.EditProfileModule.changepasswordmanufacturerTest@2a265ea9]" started-at="2023-11-23T16:11:35 IST" name="bC" finished-at="2023-11-23T16:11:43 IST" duration-ms="7858" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bC -->
        <test-method retried="true" signature="changepasswordmanufacturer()[pri:0, instance:com.Procure.EditProfileModule.changepasswordmanufacturerTest@2a265ea9]" started-at="2023-11-23T16:11:43 IST" name="changepasswordmanufacturer" finished-at="2023-11-23T16:11:45 IST" duration-ms="1676" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.EditProfileModule.changepasswordmanufacturerTest.changepasswordmanufacturer(changepasswordmanufacturerTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[changepasswordmanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[changepasswordmanufacturer----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- changepasswordmanufacturer -->
        <test-method retried="true" signature="changepasswordmanufacturer()[pri:0, instance:com.Procure.EditProfileModule.changepasswordmanufacturerTest@2a265ea9]" started-at="2023-11-23T16:11:45 IST" name="changepasswordmanufacturer" finished-at="2023-11-23T16:11:45 IST" duration-ms="667" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.EditProfileModule.changepasswordmanufacturerTest.changepasswordmanufacturer(changepasswordmanufacturerTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[changepasswordmanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[changepasswordmanufacturer----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- changepasswordmanufacturer -->
        <test-method retried="true" signature="changepasswordmanufacturer()[pri:0, instance:com.Procure.EditProfileModule.changepasswordmanufacturerTest@2a265ea9]" started-at="2023-11-23T16:11:45 IST" name="changepasswordmanufacturer" finished-at="2023-11-23T16:11:46 IST" duration-ms="449" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.EditProfileModule.changepasswordmanufacturerTest.changepasswordmanufacturer(changepasswordmanufacturerTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[changepasswordmanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[changepasswordmanufacturer----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- changepasswordmanufacturer -->
        <test-method signature="changepasswordmanufacturer()[pri:0, instance:com.Procure.EditProfileModule.changepasswordmanufacturerTest@2a265ea9]" started-at="2023-11-23T16:11:46 IST" name="changepasswordmanufacturer" finished-at="2023-11-23T16:11:46 IST" duration-ms="647" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.EditProfileModule.changepasswordmanufacturerTest.changepasswordmanufacturer(changepasswordmanufacturerTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[changepasswordmanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[changepasswordmanufacturer23/11/2023 16-11-46----TestScript execution failed-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- changepasswordmanufacturer -->
      </class> <!-- com.Procure.EditProfileModule.changepasswordmanufacturerTest -->
      <class name="com.Procure.Admin.addretailerandsearchorderTest">
        <test-method is-config="true" signature="bC()[pri:0, instance:com.Procure.Admin.addretailerandsearchorderTest@7d0b7e3c]" started-at="2023-11-23T16:11:57 IST" name="bC" finished-at="2023-11-23T16:12:02 IST" duration-ms="4861" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bC -->
        <test-method retried="true" signature="addretailerandsearchorder()[pri:0, instance:com.Procure.Admin.addretailerandsearchorderTest@7d0b7e3c]" started-at="2023-11-23T16:12:02 IST" name="addretailerandsearchorder" finished-at="2023-11-23T16:12:03 IST" duration-ms="1515" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.addretailerandsearchorderTest.addretailerandsearchorder(addretailerandsearchorderTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addretailerandsearchorder----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addretailerandsearchorder----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addretailerandsearchorder -->
        <test-method retried="true" signature="addretailerandsearchorder()[pri:0, instance:com.Procure.Admin.addretailerandsearchorderTest@7d0b7e3c]" started-at="2023-11-23T16:12:04 IST" name="addretailerandsearchorder" finished-at="2023-11-23T16:12:04 IST" duration-ms="689" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.addretailerandsearchorderTest.addretailerandsearchorder(addretailerandsearchorderTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addretailerandsearchorder----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addretailerandsearchorder----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addretailerandsearchorder -->
        <test-method retried="true" signature="addretailerandsearchorder()[pri:0, instance:com.Procure.Admin.addretailerandsearchorderTest@7d0b7e3c]" started-at="2023-11-23T16:12:04 IST" name="addretailerandsearchorder" finished-at="2023-11-23T16:12:05 IST" duration-ms="459" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.addretailerandsearchorderTest.addretailerandsearchorder(addretailerandsearchorderTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addretailerandsearchorder----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addretailerandsearchorder----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addretailerandsearchorder -->
        <test-method signature="addretailerandsearchorder()[pri:0, instance:com.Procure.Admin.addretailerandsearchorderTest@7d0b7e3c]" started-at="2023-11-23T16:12:05 IST" name="addretailerandsearchorder" finished-at="2023-11-23T16:12:05 IST" duration-ms="384" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.addretailerandsearchorderTest.addretailerandsearchorder(addretailerandsearchorderTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addretailerandsearchorder----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addretailerandsearchorder23/11/2023 16-12-05----TestScript execution failed-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addretailerandsearchorder -->
      </class> <!-- com.Procure.Admin.addretailerandsearchorderTest -->
    </test> <!-- Test -->
    <test started-at="2023-11-23T16:11:35 IST" name="Test1" finished-at="2023-11-23T16:13:14 IST" duration-ms="99205">
      <class name="com.Procure.Admin.addretailerwithmandatorytextfieldTest">
        <test-method is-config="true" signature="config_BS()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:11:34 IST" name="config_BS" finished-at="2023-11-23T16:11:35 IST" duration-ms="635" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BS -->
        <test-method is-config="true" signature="config_BC()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:11:35 IST" name="config_BC" finished-at="2023-11-23T16:11:46 IST" duration-ms="11248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BC -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:11:46 IST" name="config_BM" finished-at="2023-11-23T16:11:49 IST" duration-ms="2355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="addretailerwithmandatorytextfield()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:11:49 IST" name="addretailerwithmandatorytextfield" finished-at="2023-11-23T16:11:49 IST" duration-ms="403" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.addretailerwithmandatorytextfieldTest.addretailerwithmandatorytextfield(addretailerwithmandatorytextfieldTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addretailerwithmandatorytextfield----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addretailerwithmandatorytextfield----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addretailerwithmandatorytextfield -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:11:49 IST" name="config_AM" finished-at="2023-11-23T16:11:54 IST" duration-ms="5107" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:11:54 IST" name="config_BM" finished-at="2023-11-23T16:11:55 IST" duration-ms="856" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="addretailerwithmandatorytextfield()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:11:55 IST" name="addretailerwithmandatorytextfield" finished-at="2023-11-23T16:11:56 IST" duration-ms="399" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.addretailerwithmandatorytextfieldTest.addretailerwithmandatorytextfield(addretailerwithmandatorytextfieldTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addretailerwithmandatorytextfield----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addretailerwithmandatorytextfield----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addretailerwithmandatorytextfield -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:11:56 IST" name="config_AM" finished-at="2023-11-23T16:12:01 IST" duration-ms="5161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:12:01 IST" name="config_BM" finished-at="2023-11-23T16:12:01 IST" duration-ms="623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="addretailerwithmandatorytextfield()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:12:01 IST" name="addretailerwithmandatorytextfield" finished-at="2023-11-23T16:12:02 IST" duration-ms="288" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.addretailerwithmandatorytextfieldTest.addretailerwithmandatorytextfield(addretailerwithmandatorytextfieldTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addretailerwithmandatorytextfield----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addretailerwithmandatorytextfield----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addretailerwithmandatorytextfield -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:12:02 IST" name="config_AM" finished-at="2023-11-23T16:12:07 IST" duration-ms="5120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:12:07 IST" name="config_BM" finished-at="2023-11-23T16:12:07 IST" duration-ms="478" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method signature="addretailerwithmandatorytextfield()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:12:07 IST" name="addretailerwithmandatorytextfield" finished-at="2023-11-23T16:12:07 IST" duration-ms="184" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.addretailerwithmandatorytextfieldTest.addretailerwithmandatorytextfield(addretailerwithmandatorytextfieldTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[addretailerwithmandatorytextfield----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[addretailerwithmandatorytextfield23/11/2023 16-12-08----TestScript execution failed-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- addretailerwithmandatorytextfield -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:12:08 IST" name="config_AM" finished-at="2023-11-23T16:12:13 IST" duration-ms="5070" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_AC()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:12:13 IST" name="config_AC" finished-at="2023-11-23T16:12:13 IST" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AC -->
        <test-method is-config="true" signature="config_AS()[pri:0, instance:com.Procure.Admin.addretailerwithmandatorytextfieldTest@6e9a5ed8]" started-at="2023-11-23T16:13:14 IST" name="config_AS" finished-at="2023-11-23T16:13:14 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AS -->
      </class> <!-- com.Procure.Admin.addretailerwithmandatorytextfieldTest -->
      <class name="com.Procure.Admin.updatemanufacturerTest">
        <test-method is-config="true" signature="config_BC()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:13 IST" name="config_BC" finished-at="2023-11-23T16:12:18 IST" duration-ms="4560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BC -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:18 IST" name="config_BM" finished-at="2023-11-23T16:12:19 IST" duration-ms="1370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="updatemanufacturer()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:19 IST" name="updatemanufacturer" finished-at="2023-11-23T16:12:19 IST" duration-ms="318" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.updatemanufacturerTest.updatemanufacturer(updatemanufacturerTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[updatemanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[updatemanufacturer----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- updatemanufacturer -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:19 IST" name="config_AM" finished-at="2023-11-23T16:12:24 IST" duration-ms="5134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:24 IST" name="config_BM" finished-at="2023-11-23T16:12:25 IST" duration-ms="591" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="updatemanufacturer()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:25 IST" name="updatemanufacturer" finished-at="2023-11-23T16:12:25 IST" duration-ms="138" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.updatemanufacturerTest.updatemanufacturer(updatemanufacturerTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[updatemanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[updatemanufacturer----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- updatemanufacturer -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:25 IST" name="config_AM" finished-at="2023-11-23T16:12:30 IST" duration-ms="5183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:30 IST" name="config_BM" finished-at="2023-11-23T16:12:31 IST" duration-ms="646" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="updatemanufacturer()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:31 IST" name="updatemanufacturer" finished-at="2023-11-23T16:12:31 IST" duration-ms="103" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.updatemanufacturerTest.updatemanufacturer(updatemanufacturerTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[updatemanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[updatemanufacturer----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- updatemanufacturer -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:31 IST" name="config_AM" finished-at="2023-11-23T16:12:36 IST" duration-ms="5079" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:36 IST" name="config_BM" finished-at="2023-11-23T16:12:37 IST" duration-ms="494" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method signature="updatemanufacturer()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:37 IST" name="updatemanufacturer" finished-at="2023-11-23T16:12:37 IST" duration-ms="104" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.updatemanufacturerTest.updatemanufacturer(updatemanufacturerTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[updatemanufacturer----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[updatemanufacturer23/11/2023 16-12-37----TestScript execution failed-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- updatemanufacturer -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:37 IST" name="config_AM" finished-at="2023-11-23T16:12:42 IST" duration-ms="5077" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_AC()[pri:0, instance:com.Procure.Admin.updatemanufacturerTest@7e057f43]" started-at="2023-11-23T16:12:42 IST" name="config_AC" finished-at="2023-11-23T16:12:42 IST" duration-ms="122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AC -->
      </class> <!-- com.Procure.Admin.updatemanufacturerTest -->
      <class name="com.Procure.Admin.checkinvoicebyidTest">
        <test-method is-config="true" signature="config_BC()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:12:42 IST" name="config_BC" finished-at="2023-11-23T16:12:48 IST" duration-ms="6223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BC -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:12:48 IST" name="config_BM" finished-at="2023-11-23T16:12:50 IST" duration-ms="1898" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="checkinvoicebyid()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:12:50 IST" name="checkinvoicebyid" finished-at="2023-11-23T16:12:51 IST" duration-ms="706" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.checkinvoicebyidTest.checkinvoicebyid(checkinvoicebyidTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[checkinvoicebyid----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[checkinvoicebyid----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- checkinvoicebyid -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:12:51 IST" name="config_AM" finished-at="2023-11-23T16:12:56 IST" duration-ms="5113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:12:56 IST" name="config_BM" finished-at="2023-11-23T16:12:57 IST" duration-ms="677" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="checkinvoicebyid()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:12:57 IST" name="checkinvoicebyid" finished-at="2023-11-23T16:12:57 IST" duration-ms="299" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.checkinvoicebyidTest.checkinvoicebyid(checkinvoicebyidTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[checkinvoicebyid----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[checkinvoicebyid----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- checkinvoicebyid -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:12:57 IST" name="config_AM" finished-at="2023-11-23T16:13:02 IST" duration-ms="5134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:13:02 IST" name="config_BM" finished-at="2023-11-23T16:13:03 IST" duration-ms="413" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method retried="true" signature="checkinvoicebyid()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:13:03 IST" name="checkinvoicebyid" finished-at="2023-11-23T16:13:03 IST" duration-ms="96" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.checkinvoicebyidTest.checkinvoicebyid(checkinvoicebyidTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[checkinvoicebyid----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[checkinvoicebyid----TestScript execution Skipped-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- checkinvoicebyid -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:13:03 IST" name="config_AM" finished-at="2023-11-23T16:13:08 IST" duration-ms="5100" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_BM()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:13:08 IST" name="config_BM" finished-at="2023-11-23T16:13:08 IST" duration-ms="399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_BM -->
        <test-method signature="checkinvoicebyid()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:13:08 IST" name="checkinvoicebyid" finished-at="2023-11-23T16:13:08 IST" duration-ms="111" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.Procure.Admin.checkinvoicebyidTest.checkinvoicebyid(checkinvoicebyidTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[checkinvoicebyid----TestScript execution strts from here-----]]>
            </line>
            <line>
              <![CDATA[checkinvoicebyid23/11/2023 16-13-08----TestScript execution failed-----]]>
            </line>
          </reporter-output>
        </test-method> <!-- checkinvoicebyid -->
        <test-method is-config="true" signature="config_AM()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:13:09 IST" name="config_AM" finished-at="2023-11-23T16:13:14 IST" duration-ms="5091" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AM -->
        <test-method is-config="true" signature="config_AC()[pri:0, instance:com.Procure.Admin.checkinvoicebyidTest@6c284af]" started-at="2023-11-23T16:13:14 IST" name="config_AC" finished-at="2023-11-23T16:13:14 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config_AC -->
      </class> <!-- com.Procure.Admin.checkinvoicebyidTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
